name: "[State Machine] - Testing orquestrator"

on:
  push:
    branches: [ "*" ]

env:
  SFN: aws stepfunctions --endpoint-url http://localhost:8083


jobs:
  test-sfn:
    runs-on: ubuntu-latest
    container:
      image: amazon/aws-stepfunctions-local:latest

    steps:
      - name: Debug Environment
        run: |
          echo "PATH: $PATH"
          echo "SHELL: $SHELL"
        shell: bash

      - name: Update and Install Dependencies
        run: |
          yum update
        shell: bash

      - name: Checkout repository files
        uses: actions/checkout@v3

      - name: Check Step files
        run: ls -la
      
