name: "[State Machine] - Testing orquestrator"

on:
  push:
    branches: [ "*" ]

env:
  SFN: aws stepfunctions --endpoint-url http://localhost:8083


jobs:
  test-sfn:
    runs-on: ubuntu-latest
    container:
      image: amazon/aws-stepfunctions-local:latest

    steps:
      - name: Update and Install Dependencies
        run: |
          sudo yum update -y
          sudo yum install -y tar
          sudo yum install -y awscli

      - name: Checkout repository files
        uses: actions/checkout@v3

      - name: Check Step files
        run: ls -la
      
      - name: Testing Step Function Local
        run: $SFN list-executions
      
