name: "[State Machine] - Testing orquestrator"

on:
  push:
    branches: [ "*" ]

jobs:
  test-sfn:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository files
        uses: actions/checkout@v3
      
      - name: Downloading StepFunctionsLocal
        run: wget https://s3.amazonaws.com/stepfunctionslocal/StepFunctionsLocal.tar.gz

      - name: Extract StepFunctionsLocal
        run: tar -xvf StepFunctionsLocal.tar.gz

      - name: Check StepFunctionsLocal version
        run: java -jar StepFunctionsLocal.jar -v

      - name: Check Step files
        run: ls -la
      