name: "[State Machine] - Testing orquestrator"

on:
  push:
    branches: [ "*" ]

jobs:
  test-sfn:
    runs-on: ubuntu-latest
    container:
      image: amazon/aws-stepfunctions-local:latest
      options: 
        --user root
        --expose 8083
      env:
        AWS_DEFAULT_REGION: default
        AWS_ACCESS_KEY_ID: default
        AWS_SECRET_ACCESS_KEY: default

    steps:
      - name: Update and Install Dependencies
        run: |
          yum update -y
          yum install -y tar
          yum install -y awscli

      - name: Checkout repository files
        uses: actions/checkout@v3

      - name: Check Step files
        run: ls -la
      
      - name: Testing Step Function Local
        run: aws stepfunctions --endpoint-url http://test-sfn:8083 create-state-machine --name Test1 --role-arn "arn:aws:iam::012345678901:role/DummyRole" --definition file://state-machine-asl/one.json
      
