name: "[State Machine] - Testing orquestrator"

on: push

jobs:
  runner-job:
    runs-on: ubuntu-latest
    services:
      stepfunction:
        image: amazon/aws-stepfunctions-local:latest
        ports:
          - 8083:8083
    steps:
      - name: Checkout repository files
        uses: actions/checkout@v3

      - name: Check Step files
        run: ls -la
      
      - name: Testing Step Function Local
        run: aws stepfunctions --endpoint-url http://stepfunction:8083 create-state-machine --name "Test1" --role-arn "arn:aws:iam::012345678901:role/DummyRole" --definition file://state-machine-asl/one.json
      
